name: f-droid

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v3
        with:
          # https://gitlab.com/fdroid/fdroidclient.git
          # git@gitlab.com:fdroid/fdroidclient.git
          repository: fdroid/fdroidclient
          github-server-url: https://gitlab.com
      - name: show
        run: ls
