name: f-droid

on:
  workflow_dispatch:

# https://gitlab.com/fdroid/fdroidclient.git
# git@gitlab.com:fdroid/fdroidclient.git
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout manually
        run: |
          git clone  https://gitlab.com/fdroid/fdroidclient.git
      - name: show
        run: ls *
